namespace ApiCm.DTOs;

public sealed class TBPRODUCTODto
{
    public int PrdCompania { get; set; }
    public required string PrdCodigo { get; set; }
    public int? CiaCodigo { get; set; }
    public string? PrvCodigo { get; set; }
    public int? PaiCodigo { get; set; }
    public int TinCodigo { get; set; }
    public int? DivCodigo { get; set; }
    public int? ClaCodigo { get; set; }
    public int? MarCodigo { get; set; }
    public int? CctCodigo { get; set; }
    public int? UnmCodigo { get; set; }
    public int? PrdEstatus { get; set; }
    public int? PrdTipo { get; set; }
    public int? PrdNivel { get; set; }
    public string? PrdDescripcion { get; set; }
    public string? PrdDescripcion2 { get; set; }
    public string? PrdCodigoAlterno { get; set; }
    public string? PrdCodigoBarra { get; set; }
    public int? PrdUnidad { get; set; }
    public decimal? PrdCosto { get; set; }
    public decimal? PrdCosto2 { get; set; }
    public decimal? PrdCosto3 { get; set; }
    public decimal? PrdCosto4 { get; set; }
    public decimal? PrdCosto5 { get; set; }
    public decimal? PrdPrecio { get; set; }
    public decimal? PrdPrecio2 { get; set; }
    public decimal? PrdPrecio3 { get; set; }
    public decimal? PrdPrecio4 { get; set; }
    public decimal? PrdPrecio5 { get; set; }
    public decimal? PrdPrecio6 { get; set; }
    public decimal? PrdPrecio7 { get; set; }
    public decimal? PrdPrecio8 { get; set; }
    public decimal? PrdPrecio9 { get; set; }
    public decimal? PrdPrecio10 { get; set; }
    public decimal? PrdDesc1 { get; set; }
    public decimal? PrdDesc2 { get; set; }
    public decimal? PrdDesc3 { get; set; }
    public decimal? PrdDesc4 { get; set; }
    public decimal? PrdDesc5 { get; set; }
    public decimal? PrdStockMin { get; set; }
    public decimal? PrdStockMax { get; set; }
    public decimal? PrdStockReorden { get; set; }
    public decimal? PrdCantUlt { get; set; }
    public decimal? PrdCantDisp { get; set; }
    public decimal? PrdCantComp { get; set; }
    public decimal? PrdCantInv { get; set; }
    public decimal? PrdCantPte { get; set; }
    public decimal? PrdCantCxc { get; set; }
    public decimal? PrdCantCxp { get; set; }
    public decimal? PrdCantDev { get; set; }
    public decimal? PrdCantTrf { get; set; }
    public decimal? PrdCantPdo { get; set; }
    public decimal? PrdCantRec { get; set; }
    public DateTime? PrdFechaUlt { get; set; }
    public DateTime? PrdFechaIvt { get; set; }
    public DateTime? PrdFechaCst { get; set; }
    public DateTime? PrdFechaPrv { get; set; }
    public int? PrdDiasVto { get; set; }
    public decimal? PrdImp1 { get; set; }
    public decimal? PrdImp2 { get; set; }
    public decimal? PrdImp3 { get; set; }
    public decimal? PrdImp4 { get; set; }
    public decimal? PrdImp5 { get; set; }
    public decimal? PrdPeso { get; set; }
    public decimal? PrdVolumen { get; set; }
    public decimal? PrdAlto { get; set; }
    public decimal? PrdAncho { get; set; }
    public decimal? PrdProfundidad { get; set; }
    public decimal? PrdContenido { get; set; }
    public int? PrdUnidadContenido { get; set; }
    public string? PrdRutaFoto { get; set; }
    public string? PrdRutaAdjunto { get; set; }
    public string? PrdObservacion { get; set; }
    public DateTime? PrdFechaCrea { get; set; }
    public string? PrdUsuarioCrea { get; set; }
    public DateTime? PrdFechaMod { get; set; }
    public string? PrdUsuarioMod { get; set; }
}